image: python:3.6

stages:
  - unittest

test:
  stage: unittest
  script:
    - apt-get install graphviz
    - pip3.6 install --upgrade pip flake8
    - pip3.6 install -e .
    - pytest --verbose --durations 0 --nbval-lax
    - flake8
