image: python:3.6

stages:
  - unittest
  - documentation

before_script:
- apt-get update
- apt-get install -y graphviz
- pip3.6 install -r requirements-dev.txt
- pip3.6 install -e .

test:
  stage: unittest
  script:
    - pytest --verbose --durations 0 --nbval-lax
    - flake8

documentation:
  stage: documentation
  script:
  - pdoc --html --overwrite --html-dir public --template-dir doc-settings dagger
  - echo "helloworld" >> public/index.html
  artifacts:
    paths:
    - public
  only:
    - master
