language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
  - apt-get update
  - apt-get install -y graphviz
  - pip install --upgrade pip
install:
  - pip install .
  - pip install .[dev]
script:
  - pytest